### ISSUE TITLE
Zomertijd / Wintertijd conversie

### ISSUE THREAD

**Issue by broodroosterdev** [broodroosterdev/WindesheimtoiCal#4]
Op dit moment draait het systeem nog steeds in zomertijd modus omdat ik alleen 2 uur van de tijd afhaal ipv correct de datum te parsen en de datum afwijking mee te nemen. Hopelijk kan dit opgelost worden door de tijdzone in de ical aan te passen.

**Comment by broodroosterdev** [comment]
Currently added warnings to both website and appointments themselves.

**Comment by gerben838665** [comment]
Ik heb een pull request gestuurd met hierin een fix voor het zomertijd / wintertijd probleem. #5

**Comment by broodroosterdev** [comment]
@gerben838665 Bedankt! Ik kon maar niet uitvogelen wat er fout ging met moment.js. Ik zal het mergen en op de server gooien.

**Comment by sems** [comment]
@broodroosterdev Nu de tijd weer gefixed is, misschien een idee om de melding te verwijderen dat de tijden niet kloppen :D

**Comment by broodroosterdev** [comment]
Ik heb nu het nu op de server gegooid en getest dat er geen meldingen meer zijn dat de tijden niet kloppen.
